# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release Deploy-SIT
# env:
  # NODE_EXTRA_CA_CERTS: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
  

on:
 workflow_dispatch:
 push:
   branches: 
   - release**
 pull_request:
   branches:
   - release**
 
jobs:
  build:

    runs-on: RUNNER-LINUX3-134


    steps:
    - shell: bash
      run: |
          echo "Cleaning workspace directory..."
          sudo rm -rfv ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}
   
    - uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn -s /data/JBuild-Red-Prod/tools/nexus/.m2/settings.xml clean install  --file pom.xml
      
      
    - name: Copy Binary To SCM folder For Prod Package 
      run: |    
         BRANCH_NAME="$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
         REPO="$(echo ${GITHUB_REPOSITORY#refs/heads/} | sed 's/\//_/g')"
         mkdir -p /data/Github-Package/$REPO-$BRANCH_NAME
         cp target/casa_*.war /data/Github-Package/$REPO-$BRANCH_NAME
          
  
  deploy-sit:
      #  if: github.event_name == 'push'
        runs-on: RUNNER-LINUX3-134
        needs: 
        - build
        
        steps:
        - name: Cleanup SCM Tmp Folder
          uses: appleboy/ssh-action@master
          with:
           host:  172.30.2.107
           username: jbossadm
           password: ${{ secrets.JBOSSADM_172_30_2_107 }}
           port: 22
           script: |
            cd /app/jboss/EAP-7.1.0/standalone/tmp/scm
            pwd
            rm casa_*.war
       
        - name: Copy War file to SCM Tmp Folder
          uses: appleboy/scp-action@master
          with:
           host: 172.30.2.107
           username: jbossadm
           password: ${{ secrets.JBOSSADM_172_30_2_107 }}
           port: 22
           source: "target/casa_*.war"
           target: "/app/jboss/EAP-7.1.0/standalone/tmp/scm"
           strip_components: 1
       
        - name: Execution Step
          uses: appleboy/ssh-action@master
          with:
           host:  172.30.2.107
           username: jbossadm
           password: ${{ secrets.JBOSSADM_172_30_2_107 }}
           port: 22
           script: |
            cd /app/jboss/EAP-7.1.0/standalone/deployments
            pwd
            rm casa_*.war casa_*.war.deployed
            sleep 20s
            rm casa_*.war.undeployed
            cp /app/jboss/EAP-7.1.0/standalone/tmp/scm/casa_*.war /app/jboss/EAP-7.1.0/standalone/deployments
            sleep 60s
            ls -lrt
                  
                
  
                  
          
            
