# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release Deploy-UAT
# env:
  # NODE_EXTRA_CA_CERTS: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
  

on:
 workflow_dispatch:
 
 
jobs:
  build:

    runs-on: RUNNER-LINUX3-134


    steps:
    - shell: bash
      run: pwd
           
  
  deploy-uat:
        runs-on: RUNNER-LINUX3-134
        needs: 
        - build
        
        steps:
        - name: Prepare War-File from SIT 
          run: |
             echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
             echo "GITHUB_REF=$GITHUB_REF"
             BRANCH_NAME="$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
             REPO="$(echo ${GITHUB_REPOSITORY#refs/heads/} | sed 's/\//_/g')"
             cp  /data/Github-Package/$REPO-$BRANCH_NAME/*.war  target/

        
        - name: Cleanup SCM Tmp Folder
          uses: appleboy/ssh-action@master
          with:
           host:  172.30.2.109
           username: jbossadm
           password: ${{ secrets.JBOSSADM_172_30_2_109 }}
           port: 22
           script: |
            cd /app/jboss/EAP-7.1.0/standalone/tmp/scm
            pwd
            rm -r casa_*.war
         
        - name: Copy War file to SCM Tmp Folder
          uses: appleboy/scp-action@master
          with:
           host: 172.30.2.109
           username: jbossadm
           password: ${{ secrets.JBOSSADM_172_30_2_109 }}
           port: 22
           source: "target/casa_*.war"
           target: "/app/jboss/EAP-7.1.0/standalone/tmp/scm"
           strip_components: 1
       
        - name: Execution Step
          uses: appleboy/ssh-action@master
          with:
           host:  172.30.2.109
           username: jbossadm
           password: ${{ secrets.JBOSSADM_172_30_2_109 }}
           port: 22
           script: |
            cd /app/jboss/EAP-7.1.0/standalone/deployments
            pwd
            rm casa_*.war casa_*.war.deployed
            sleep 20s
            rm casa_*.war.undeployed
            cp /app/jboss/EAP-7.1.0/standalone/tmp/scm/casa_*.war /app/jboss/EAP-7.1.0/standalone/deployments
            sleep 60s
            ls -lrt
                  
                
  
                  
          
   
